Repository rogemus/FoodHub, pull requests merged in 2019-01, with the labels that each got.

#14 Update package.json
  .gitignore
  client/package-lock.json
  client/package.json
Labels: frontend, setup

#10 Home Page
  client/package-lock.json
  client/package.json
  client/src/helpers/uuid.helper.js
  client/src/img/img1.jpg
  client/src/img/img2.jpeg
  client/src/img/img3.jpeg
  client/src/img/img4.jpg
  client/src/img/img5.jpg
  client/src/img/img6.jpg
  client/src/img/img7.jpg
  client/src/img/img8.jpg
  client/src/index.html
  client/src/styles/base/_body.pcss
  client/src/styles/base/_typography.pcss
  client/src/styles/base/base.pcss
  client/src/styles/components/components.pcss
  client/src/styles/components/logo/_logo.pcss
  client/src/styles/components/navigation/_navigation.pcss
  client/src/styles/components/tile/_tile.pcss
  client/src/styles/components/tiles/_tiles.pcss
  client/src/styles/components/wrapper/_page-wrapper.pcss
  client/src/styles/components/wrapper/_wrapper.pcss
  client/src/styles/configs/_colors.pcss
  client/src/styles/configs/_text.pcss
  client/src/styles/configs/configs.pcss
  client/src/styles/main.pcss
  client/src/view/app.js
  client/src/view/pages/home/homePage.js
  client/src/view/shared/navigation/navigation.js
  client/src/view/shared/navigation/styles.pcss
  client/src/view/shared/tile/tile.js
  client/webpack/configs/postcss.config.js
Labels: feature, frontend

#20 Add create, login and me endpoints
  server/accounts/serializers.py
  server/accounts/urls.py
  server/accounts/utils.py
  server/accounts/views.py
  server/foodhub/permissions.py
  server/foodhub/urls.py
  server/requirements.txt
Labels: backend

#21 Add recipes app
  server/foodhub/settings.py
  server/recipes/__init__.py
  server/recipes/admin.py
  server/recipes/apps.py
  server/recipes/migrations/0001_initial.py
  server/recipes/migrations/__init__.py
  server/recipes/models.py
  server/recipes/tests.py
  server/recipes/views.py
Labels: backend

#31 8 recipe page
  client/package-lock.json
  client/src/actions/actionTypes.js
  client/src/actions/recipes.actions.js
  client/src/index.html
  client/src/reducers/recipes.reducer.js
  client/src/styles/components/components.pcss
  client/src/styles/components/logo/_logo.pcss
  client/src/styles/components/recipes/_recipes.pcss
  client/src/view/app.js
  client/src/view/pages/currentUser/currentUserPage.js
  client/src/view/pages/home/homePage.js
  client/src/view/pages/logout/logoutPage.js
  client/src/view/pages/recipes/recipePage.js
  client/src/view/pages/recipes/recipesAddPage.js
  client/src/view/pages/recipes/recipesPage.js
  client/src/view/shared/navigation/navigation.js
  client/src/view/shared/tile/tile.js
  client/webpack/configs/devServer.config.js
Labels: feature, frontend

#33 add 404 page
  client/src/styles/components/components.pcss
  client/src/styles/components/errors/_404.pcss
  client/src/view/app.js
  client/src/view/pages/errors/404Page.js
Labels: feature, frontend
